# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 592)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(800, 300))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.mainLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.labelDepth = QtWidgets.QLabel(self.layoutWidget)
        self.labelDepth.setObjectName("labelDepth")
        self.mainLayout.addWidget(self.labelDepth, 3, 2, 1, 1)
        self.spinDepth = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinDepth.setMaximum(200)
        self.spinDepth.setProperty("value", 100)
        self.spinDepth.setObjectName("spinDepth")
        self.mainLayout.addWidget(self.spinDepth, 3, 3, 1, 1)
        self.spinWidth = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinWidth.setMinimum(100)
        self.spinWidth.setMaximum(10000)
        self.spinWidth.setProperty("value", 1920)
        self.spinWidth.setObjectName("spinWidth")
        self.mainLayout.addWidget(self.spinWidth, 0, 3, 1, 1)
        self.labelWidth = QtWidgets.QLabel(self.layoutWidget)
        self.labelWidth.setObjectName("labelWidth")
        self.mainLayout.addWidget(self.labelWidth, 0, 2, 1, 1)
        self.spinHeight = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinHeight.setMinimum(100)
        self.spinHeight.setMaximum(10000)
        self.spinHeight.setProperty("value", 1080)
        self.spinHeight.setObjectName("spinHeight")
        self.mainLayout.addWidget(self.spinHeight, 1, 3, 1, 1)
        self.labelHeight = QtWidgets.QLabel(self.layoutWidget)
        self.labelHeight.setObjectName("labelHeight")
        self.mainLayout.addWidget(self.labelHeight, 1, 2, 1, 1)
        self.spinThreads = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinThreads.setMinimum(1)
        self.spinThreads.setMaximum(10)
        self.spinThreads.setProperty("value", 4)
        self.spinThreads.setObjectName("spinThreads")
        self.mainLayout.addWidget(self.spinThreads, 4, 3, 1, 1)
        self.listImages = QtWidgets.QListWidget(self.layoutWidget)
        self.listImages.setObjectName("listImages")
        self.mainLayout.addWidget(self.listImages, 0, 0, 5, 1)
        self.btnRun = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRun.setObjectName("btnRun")
        self.mainLayout.addWidget(self.btnRun, 7, 2, 1, 2)
        self.labelRadius = QtWidgets.QLabel(self.layoutWidget)
        self.labelRadius.setObjectName("labelRadius")
        self.mainLayout.addWidget(self.labelRadius, 2, 2, 1, 1)
        self.spinRadius = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinRadius.setMaximum(50)
        self.spinRadius.setProperty("value", 10)
        self.spinRadius.setObjectName("spinRadius")
        self.mainLayout.addWidget(self.spinRadius, 2, 3, 1, 1)
        self.labelThreads = QtWidgets.QLabel(self.layoutWidget)
        self.labelThreads.setObjectName("labelThreads")
        self.mainLayout.addWidget(self.labelThreads, 4, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.mainLayout.addWidget(self.progressBar, 7, 0, 1, 1)
        self.btnSelect = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSelect.setObjectName("btnSelect")
        self.mainLayout.addWidget(self.btnSelect, 5, 0, 1, 4)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Adjust Images (By Cycoe)"))
        self.labelDepth.setText(_translate("mainWindow", "浸入深度"))
        self.labelWidth.setText(_translate("mainWindow", "宽度"))
        self.labelHeight.setText(_translate("mainWindow", "高度"))
        self.btnRun.setText(_translate("mainWindow", "点击开始"))
        self.labelRadius.setText(_translate("mainWindow", "模糊半径"))
        self.labelThreads.setText(_translate("mainWindow", "线程数"))
        self.btnSelect.setText(_translate("mainWindow", "选取图像"))
